FROM ubuntu:22.04

RUN apt update && apt-get install -y python3 python3-pip
RUN pip3 install flask==3.0.* mysql-connector-python==8.0.33

COPY app.py /

ENV FLASK_APP=app
EXPOSE 8080
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "8080"]
